### ISSUE TITLE
'code': -32015, 'message': 'VM execution error.', 'data': 'Bad jump destination 2'

### ISSUE THREAD

**Issue by dimworm** [blockchain-etl/ethereum-etl#113]
Every time I export data from blocks 01000000-01099999, there will be this error:

`2018-10-23 15:13:22,817 - ProgressLogger [INFO] - Started work.
2018-10-23 15:13:47,147 - ProgressLogger [INFO] - Finished work. Total items processed: 3053. Took 0:00:24.330398.
2018-10-23 15:13:47,150 - CompositeItemExporter [INFO] - contract items exported: 3053
2018-10-23 15:13:47 Extracting token_address from token_transfers file output/token_transfers/start_block=01000000/end_block=01099999/token_transfers_01000000_01099999.csv
2018-10-23 15:13:47 Exporting tokens from blocks 01000000-01099999 to output/tokens/start_block=01000000/end_block=01099999/tokens_01000000_01099999.csv
2018-10-23 15:13:47,931 - ProgressLogger [INFO] - Started work.
Traceback (most recent call last):
  File "export_tokens.py", line 54, in <module>
    job.run()
  File "/home/jar/ethereum-etl/ethereumetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/jar/ethereum-etl/ethereumetl/jobs/export_tokens_job.py", line 55, in _end
    self.batch_work_executor.shutdown()
  File "/home/jar/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 65, in shutdown
    self.executor.shutdown()
  File "/home/jar/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/jar/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jar/ethereum-etl/ethereumetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/home/jar/ethereum-etl/ethereumetl/jobs/export_tokens_job.py", line 43, in _export
    self.batch_work_executor.execute(self.token_addresses_iterable, self._export_tokens)
  File "/home/jar/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/home/jar/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/home/jar/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jar/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/home/jar/ethereum-etl/ethereumetl/jobs/export_tokens_job.py", line 47, in _export_tokens
    self._export_token(token_address)
  File "/home/jar/ethereum-etl/ethereumetl/jobs/export_tokens_job.py", line 50, in _export_token
    token = self.token_service.get_token(token_address)
  File "/home/jar/ethereum-etl/ethereumetl/service/eth_token_service.py", line 42, in get_token
    total_supply = self._call_contract_function(contract.functions.totalSupply())
  File "/home/jar/ethereum-etl/ethereumetl/service/eth_token_service.py", line 60, in _call_contract_function
    default_value=None)
  File "/home/jar/ethereum-etl/ethereumetl/service/eth_token_service.py", line 76, in call_contract_function
    raise ex
  File "/home/jar/ethereum-etl/ethereumetl/service/eth_token_service.py", line 70, in call_contract_function
    result = func.call()
  File "/home/jar/.local/lib/python3.6/site-packages/web3/contract.py", line 1120, in call
    **self.kwargs
  File "/home/jar/.local/lib/python3.6/site-packages/web3/contract.py", line 1369, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/jar/.local/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/jar/.local/lib/python3.6/site-packages/web3/eth.py", line 294, in call
    [transaction, block_identifier],
  File "/home/jar/.local/lib/python3.6/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'Bad jump destination 2'}
2018-10-23 15:13:54 An error occurred. Quitting.
`

**Comment by medvedev1088** [comment]
Thanks for reporting this. I will look into this issue.

**Comment by medvedev1088** [comment]
@dimworm what options do you use to start the exporting process?

**Comment by dimworm** [comment]
./export_all.sh -s 2000000 -e 6499999 -b 100000 -p file:/home/jar/.local/share/io.parity.ethereum/jsonrpc.ipc -o output

**Comment by dimworm** [comment]
This error is fixed. thank you.

**Comment by medvedev1088** [comment]
@dimworm did the PR https://github.com/blockchain-etl/ethereum-etl/pull/115 help or the issue disappeared by itself?

**Comment by dimworm** [comment]
Yes, PR #115 helps.  Thank you so much.

**Comment by medvedev1088** [comment]
Reopening as the fix also ignores other errors that shouldn't be ignored.

**Comment by medvedev1088** [comment]
Seems the issue happens only with Parity.

**Comment by medvedev1088** [comment]
Merged https://github.com/blockchain-etl/ethereum-etl/pull/115 as a temporary fix.
