### ISSUE TITLE
/ethereum-etl/ethereumetl/jobs/export_contracts_job.py", line 66, in _export_contracts     result = response['result']

### ISSUE THREAD

**Issue by dimworm** [blockchain-etl/ethereum-etl#118]
My another server run into this error:

`2018-10-27 02:03:17,921 - ProgressLogger [INFO] - Started work.
2018-10-27 02:03:50,923 - ProgressLogger [INFO] - 5000 items processed.
2018-10-27 02:04:00,381 - ProgressLogger [INFO] - 10000 items processed.
Traceback (most recent call last):
  File "export_contracts.py", line 58, in <module>
    job.run()
  File "/root/ethereum-etl/ethereumetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/root/ethereum-etl/ethereumetl/jobs/export_contracts_job.py", line 87, in _end
    self.batch_work_executor.shutdown()
  File "/root/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 65, in shutdown
    self.executor.shutdown()
  File "/root/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/root/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/root/ethereum-etl/ethereumetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/root/ethereum-etl/ethereumetl/jobs/export_contracts_job.py", line 56, in _export
    self.batch_work_executor.execute(self.contract_addresses_iterable, self._export_contracts)
  File "/root/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/root/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/root/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/root/ethereum-etl/ethereumetl/jobs/export_contracts_job.py", line 66, in _export_contracts
    result = response['result']
KeyError: 'result'
2018-10-27 02:04:03 An error occurred. Quitting.`

**Comment by medvedev1088** [comment]
Thank you for reporting this. I added handling of a missing 'result' field in the json response https://github.com/blockchain-etl/ethereum-etl/pull/119. The error message should be more descriptive now and will help identify the cause.
