### ISSUE TITLE
ConflictResolution Error

### ISSUE THREAD

**Issue by iter-io** [blockchain-etl/ethereum-etl#141]
@medvedev1088 - I started getting a dependency resolution error in my recent builds of the ethereum-etl docker container.  I made this change to get it running again:

https://github.com/iter-io/ethereum-etl/commit/bde116ad06f4fc5ac0b9a705e2fd54f2acf451d7

Wasn't sure about doing a pull request though since I haven't run the tests.  Just getting into that.

**Comment by medvedev1088** [comment]
Thanks for reporting this. I tried `docker build -t ethereum-etl:latest .` and got this warning 

> eth-keys 0.2.1 has requirement eth-utils<2.0.0,>=1.3.0, but you'll have eth-utils 1.2.0 which is incompatible.

Is it what you're referring to?

**Comment by iter-io** [comment]
Yes I am getting this warning:

eth-keys 0.2.1 has requirement eth-utils<2.0.0,>=1.3.0, but you'll have
eth-utils 1.2.0 which is incompatible.

I thought my build failed as a result of this but it's succeeding right now.

**Comment by medvedev1088** [comment]
Thanks, I'll need to fix it anyway.

**Comment by deerdear** [comment]
Hi, my build is still failing with this error:

```
| => ethereumetl export_blocks_and_transactions --start-block 6988615 --end-block 7183923 --provider-uri https://mainnet.infura.io --blocks-output blocks.csv --transactions-output transactions.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.2.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('eth-utils<2.0.0,>=1.3.0'), {'eth-keys'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/../../usr/local/bin/ethereumetl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.2.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('eth-utils<2.0.0,>=1.3.0'), {'eth-keys'})
```

**Comment by medvedev1088** [comment]
Try the fix proposed by @iter-io. If it works I will create a PR and merge it. Thanks.

**Comment by luolixuan** [comment]
Hi, when I want to install ethereum-etl, eth-abi and mythril together, it has a version problem.
ethereum-etl 1.3.0 has requirement eth-abi==1.2.0, but you'll have eth-abi 1.3.0 which is incompatible.
mythril 0.20.5 has requirement eth-abi==1.3.0, but you'll have eth-abi 1.2.0 which is incompatible.
what can I do?
