### ISSUE TITLE
ValueError: result is None in response (export_all)

### ISSUE THREAD

**Issue by minhtrih** [blockchain-etl/ethereum-etl#153]
I run it on ubuntu

> ethereumetl export_all -s 4900000 -e 4999999 -b 100000 -p https://mainnet.infura.io -o output

but after n time it has error:

`File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 70, in _export           │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 70, in _export
    total_items=self.end_block - self.start_block + 1                                                                │    total_items=self.end_block - self.start_block + 1
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 48, in execute    │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)                                               │    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 31, in submit      │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()                                                                                  │    self._check_completed_futures()
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_compl│  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_comp
eted_futures                                                                                                         │leted_futures
    future.result()                                                                                                  │    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result                                         │  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()                                                                                       │    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result                                   │  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception                                                                                            │    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                            │  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)                                                                      │    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_│  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe
execute                                                                                                              │_execute
    work_handler(batch)                                                                                              │    work_handler(batch)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in _export_batch     │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in _export_batch
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]                                    │    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in <listcomp>        │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in <listcomp>
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]                                    │    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/utils.py", line 58, in rpc_response_batch_to_results      │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/utils.py", line 58, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)                                                                      │    yield rpc_response_to_result(response_item)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/utils.py", line 67, in rpc_response_to_result             │  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/utils.py", line 67, in rpc_response_to_result
    raise ValueError(error_message)                                                                                  │    raise ValueError(error_message)
ValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'error': {'code': -32603, 'message': 'request proc│ValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'error': {'code': -32603, 'message': 'request pro
essing failed'}}.`

**Comment by medvedev1088** [comment]
Thanks for reporting this. Enabling the retry mechanism for such kinds of errors should help with this issue.

**Comment by mariusndini** [comment]
I too am running into this issue constantly. Is there a work around of any kind? Some documentation n the Retry Mechanism? For me it seems to constantly be happening around blocks 4 million.

**Comment by medvedev1088** [comment]
Please try this fix https://github.com/blockchain-etl/ethereum-etl/pull/170 and let us know if it works. Note that I haven't tested the fix myself.

**Comment by mariusndini** [comment]
Unfortunately same error even with the change :/
My current work around for this is to lower the amt of data that I pull back.



$ ethereumetl export_blocks_and_transactions --start-block 4100000 --end-block 4500000 --provider-uri https://mainnet.infura.io --blocks-output blocks4.5m.csv --transactions-output transactions4.5m.csv
Symbolic Execution not available: No module named 'mythril'
pyetherchain not available: No module named 'pyetherchain'
2019-04-25 10:41:43,791 - ProgressLogger [INFO] - Started work. Items to process: 400001.
2019-04-25 10:49:05,115 - ProgressLogger [INFO] - 40100 items processed. Progress is 10%.
2019-04-25 10:58:32,560 - ProgressLogger [INFO] - 80100 items processed. Progress is 20%.
2019-04-25 11:08:05,785 - ProgressLogger [INFO] - 120100 items processed. Progress is 30%.
Traceback (most recent call last):
  File "/usr/local/bin/ethereumetl", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/cli/export_blocks_and_transactions.py", line 66, in export_blocks_and_transactions
    job.run()
  File "/usr/local/lib/python3.7/site-packages/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_blocks_job.py", line 90, in _end
    self.batch_work_executor.shutdown()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 67, in shutdown
    self.executor.shutdown()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/blockchainetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_blocks_job.py", line 70, in _export
    total_items=self.end_block - self.start_block + 1
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 50, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 55, in _fail_safe_execute
    work_handler(batch)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in _export_batch
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in <listcomp>
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/utils.py", line 71, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/utils.py", line 83, in rpc_response_to_result
    raise ValueError(error_message)
ValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'error': {'code': -32603, 'message': 'request processing failed'}}.

**Comment by medvedev1088** [comment]
Have you installed the fix using `pip3 install -e . `?

**Comment by mariusndini** [comment]
Yes, I have tried the above. Uninstalling and reinstalling and then also trying the above. at every step it cannot download in entirety. Is it because I am Infura? would this problem go away if i attempted it on my own synced geth node?

**Comment by mariusndini** [comment]
I am also curious on the pattern of failures. 
`ethereumetl export_blocks_and_transactions --start-block 4200000 --end-block 4300000 --provider-uri https://mainnet.infura.io --blocks-output blocks4.3m.csv --transactions-output transactions4.3m.csv`

I ran the code above and it failed twice.
```
2019-04-26 09:32:04,700 - ProgressLogger [INFO] - Started work. Items to process: 100001.
2019-04-26 09:34:39,113 - ProgressLogger [INFO] - 10100 items processed. Progress is 10%.
```
Above at just 10% and below at 90%. 

```
2019-04-26 09:04:40,657 - ProgressLogger [INFO] - Started work. Items to process: 100001.
2019-04-26 09:07:38,270 - ProgressLogger [INFO] - 10100 items processed. Progress is 10%.
^[[1;2C2019-04-26 09:10:49,184 - ProgressLogger [INFO] - 20100 items processed. Progress is 20%.
2019-04-26 09:13:55,665 - ProgressLogger [INFO] - 30100 items processed. Progress is 30%.
2019-04-26 09:16:52,880 - ProgressLogger [INFO] - 40100 items processed. Progress is 40%.
2019-04-26 09:20:14,724 - ProgressLogger [INFO] - 50100 items processed. Progress is 50%.
2019-04-26 09:23:13,186 - ProgressLogger [INFO] - 60100 items processed. Progress is 60%.
2019-04-26 09:26:01,226 - ProgressLogger [INFO] - 70100 items processed. Progress is 70%.
2019-04-26 09:28:48,042 - ProgressLogger [INFO] - 80100 items processed. Progress is 80%.
2019-04-26 09:31:09,348 - ProgressLogger [INFO] - 90100 items processed. Progress is 90%.

```

**Comment by jensenity** [comment]
I'm getting this error as well with running it on airflow.

`
[2019-06-05 00:49:27,605] {logging_mixin.py:95} INFO - [2019-06-05 00:49:27,605] {progress_logger.py:51} INFO - Started work. Items to process: 6342.
[2019-06-05 00:49:46,582] {logging_mixin.py:95} INFO - [2019-06-05 00:49:46,582] {progress_logger.py:70} INFO - 700 items processed. Progress is 11%.
[2019-06-05 00:49:51,324] {logging_mixin.py:95} INFO - [2019-06-05 00:49:51,323] {progress_logger.py:70} INFO - 1300 items processed. Progress is 20%.
[2019-06-05 00:50:00,561] {logging_mixin.py:95} INFO - [2019-06-05 00:50:00,561] {progress_logger.py:70} INFO - 2000 items processed. Progress is 31%.
[2019-06-05 00:50:10,565] {logging_mixin.py:95} INFO - [2019-06-05 00:50:10,565] {progress_logger.py:70} INFO - 2600 items processed. Progress is 40%.
[2019-06-05 00:50:17,569] {logging_mixin.py:95} INFO - [2019-06-05 00:50:17,569] {progress_logger.py:70} INFO - 3200 items processed. Progress is 50%.
[2019-06-05 00:50:23,673] {logging_mixin.py:95} INFO - [2019-06-05 00:50:23,673] {progress_logger.py:70} INFO - 3900 items processed. Progress is 61%.
[2019-06-05 00:50:31,420] {logging_mixin.py:95} INFO - [2019-06-05 00:50:31,420] {progress_logger.py:70} INFO - 4500 items processed. Progress is 70%.
[2019-06-05 00:50:37,754] {logging_mixin.py:95} INFO - [2019-06-05 00:50:37,754] {progress_logger.py:70} INFO - 5100 items processed. Progress is 80%.
[2019-06-05 00:50:43,624] {logging_mixin.py:95} INFO - [2019-06-05 00:50:43,624] {progress_logger.py:70} INFO - 5800 items processed. Progress is 91%.
[2019-06-05 00:52:00,048] {__init__.py:1580} ERROR - result is None in response {'jsonrpc': '2.0', 'id': 0, 'error': {'code': -32603, 'message': 'request processing failed'}}.`

It runs for a bit around 91% and then comes out with this error at the end.

Any idea how to go around with this error?

**Comment by medvedev1088** [comment]
Thanks for reporting it. I just merged this fix https://github.com/blockchain-etl/ethereum-etl/pull/170. 

Tested it with this code:

```
ethereumetl export_blocks_and_transactions --start-block 4200000 --end-block 4300000 --provider-uri https://mainnet.infura.io --blocks-output blocks4.3m.csv --transactions-output transactions4.3m.csv
```

Please help install the latest version from the develop branch with `pip3 install -e .`, then verify if the issue went away. If everything works I'll publish it to pip.

**Comment by medvedev1088** [comment]
@jensenity did you have a chance to try out the code with the fix?
