### ISSUE TITLE
Error with geth.ipc (But now with parity)

### ISSUE THREAD

**Issue by fdecollibus** [blockchain-etl/ethereum-etl#187]
Hi, first of all thank you for the amazing work you have done. 
I am just curious about an issue I am encountering.
When I try this export (very small number) I get this error 
ethereumetl export_all -s 0 -e 1000 -b 100 -p file:///mnt/hdd_data/geth/geth.ipc -o output

2019-08-28 07:35:44,646 - export_all [INFO] - Exporting blocks 00000000-00000099 to output/blocks/start_block=00000000/end_block=00000099/blocks_00000000_00000099.csv
2019-08-28 07:35:44,646 - export_all [INFO] - Exporting transactions from blocks 00000000-00000099 to output/transactions/start_block=00000000/end_block=00000099/transactions_00000000_00000099.csv
2019-08-28 07:35:44,646 - ProgressLogger [INFO] - Started work. Items to process: 100.
Traceback (most recent call last):
  File "/home/frdeco/ethlv3/bin/ethereumetl", line 10, in <module>
    sys.exit(cli())
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/cli/export_all.py", line 124, in export_all
    output_dir, provider_uri, max_workers, export_batch_size)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/jobs/export_all_common.py", line 124, in export_all_common
    job.run()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/jobs/export_blocks_job.py", line 90, in _end
    self.batch_work_executor.shutdown()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/executors/batch_work_executor.py", line 67, in shutdown
    self.executor.shutdown()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/executors/batch_work_executor.py", line 55, in _fail_safe_execute
    work_handler(batch)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in _export_batch
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/jobs/export_blocks_job.py", line 77, in <listcomp>
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/mappers/block_mapper.py", line 50, in json_dict_to_block
    block.size = hex_to_dec(json_dict.get('size'))
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/ethereumetl/utils.py", line 34, in hex_to_dec
    return int(hex_string, 16)
TypeError: int() can't convert non-string with explicit base

Which I don't get at all when I use the json-rpc3.ipc file from Parity or the infura network... what could have happened? 

Thanks again for your amazing work

**Comment by medvedev1088** [comment]
That's strange. What version of geth are you running? 

I've just tried it with Geth/v1.9.2-stable-e76047e9/darwin-amd64/go1.12.7 and it succeeded.

**Comment by fdecollibus** [comment]
Hi, I tried a clean installation and it worked, pretty weird... but thank you for your time
