### ISSUE TITLE
ExportAll stops with "TypeError: int() can't convert non-string with explicit base" after block 7200000

### ISSUE THREAD

**Issue by fdecollibus** [blockchain-etl/ethereum-etl#190]
Hi

I've tried both parity and ethereum, but this error persists..

2019-11-03 17:55:30,441 - export_all [INFO] - Exporting transactions from blocks 07200000-07200099 to data2/transactions/start_block=07200000/end_block=07200099/transactions_07200000_07200099.csv
2019-11-03 17:55:30,441 - ProgressLogger [INFO] - Started work. Items to process: 100.
Traceback (most recent call last):
  File "/home/frdeco/ethlv3/bin/ethereumetl", line 11, in <module>
    load_entry_point('ethereum-etl', 'console_scripts', 'ethereumetl')()
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frdeco/ethlv3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/cli/export_all.py", line 124, in export_all
    output_dir, provider_uri, max_workers, export_batch_size)
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/jobs/export_all_common.py", line 124, in export_all_common
    job.run()
  File "/mnt/hdd_data/parity/etl/ethereum-etl/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 90, in _end
    self.batch_work_executor.shutdown()
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 97, in shutdown
    self.executor.shutdown()
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 77, in _export_batch
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 77, in <listcomp>
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/mappers/block_mapper.py", line 50, in json_dict_to_block
    block.size = hex_to_dec(json_dict.get('size'))
  File "/mnt/hdd_data/parity/etl/ethereum-etl/ethereumetl/utils.py", line 34, in hex_to_dec
    return int(hex_string, 16)
TypeError: int() can't convert non-string with explicit base

**Comment by medvedev1088** [comment]
Check if this similar issue helps https://github.com/blockchain-etl/ethereum-etl/issues/187

**Comment by fdecollibus** [comment]
Incredible, I updated ethereumetl, tried again with parity ipc, and now seems to work, I am waiting for the export to finish, thank you so much for your incredible work

**Comment by fdecollibus** [comment]
Just one last thing: do  sporadic exceptions in logs like 
 2019-11-04 07:24:56,298 - evmdasm.disassembler [ERROR] - invalid instruction: PUSH32
means something is wrong with my disassembler version or I can safely ignore them?
