### ISSUE TITLE
pip3 install ethereum-etl[streaming] fails (Error compiling Cython file)

### ISSUE THREAD

**Issue by meowsbits** [blockchain-etl/ethereum-etl#192]
```
$ pip3 install ethereum-etl[streaming]


Collecting ethereum-etl[streaming]
  Using cached https://files.pythonhosted.org/packages/40/b3/ba3f2d053fc403e55fcc17740858579ff5e3a630b864f6b153bc4f763ef2/ethereum-etl-1.3.1.tar.gz
Collecting click==7.0 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting eth-abi==1.2.0 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/3d/4e/66d711f39c892c295cd61d2a241d26e4fa253e483382bdb34e39ea4c4d96/eth_abi-1.2.0-py3-none-any.whl
Collecting eth-utils==1.3.0 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/ac/96/5b6e33beeabd23df64294a023d7c7b835cf9382b042155c90608d936a9b3/eth_utils-1.3.0-py3-none-any.whl
Collecting ethereum-dasm==0.1.4 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/6f/f1/9556efc3b5a80254a9376bfc339aafb33579429c78b03272a9204f90b1a7/ethereum_dasm-0.1.4-py3-none-any.whl
Collecting python-dateutil==2.7.0 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/bc/c5/3449988d33baca4e9619f49a14e28026399b0a8c32817e28b503923a04ab/python_dateutil-2.7.0-py2.py3-none-any.whl
Collecting web3==4.7.2 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/68/d4/ce134aed18f5989f1facae736a7d1ccb3306576206f09a6b712660387f05/web3-4.7.2-py3-none-any.whl
Collecting google-cloud-pubsub==0.39.1 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/c0/9a/4455b1c1450e9b912855b58ca6eee7a27ff1e9b52e4d98c243d93256f469/google_cloud_pubsub-0.39.1-py2.py3-none-any.whl
Collecting timeout-decorator==0.4.1 (from ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/07/1c/0d9adcb848f1690f3253dcb1c1557b6cf229a93e724977cb83f266cbd0ae/timeout-decorator-0.4.1.tar.gz
Collecting eth-typing<=2 (from eth-abi==1.2.0->ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/88/df/19e17ca63aa0285ef0c2e95231f2f6a8d99a69ee58817c22b6b417067460/eth_typing-2.0.0-py3-none-any.whl
Collecting parsimonious==0.8.0 (from eth-abi==1.2.0->ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/4a/89/32c55944cd30dff856f16859ee325b13c83c260d0c56c0eed511e8063c87/parsimonious-0.8.0.tar.gz
Collecting eth-hash<1.0.0,>=0.1.0 (from eth-utils==1.3.0->ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/0d/d8/0f0c8d4ccaa4c8d25524fd1ed9f5c6d9551b52b74b973f338de3f0a23111/eth_hash-0.2.0-py3-none-any.whl
Collecting cytoolz<1.0.0,>=0.8.2; implementation_name == "cpython" (from eth-utils==1.3.0->ethereum-etl[streaming])
  Using cached https://files.pythonhosted.org/packages/62/b1/7f16703fe4a497879b1b457adf1e472fad2d4f030477698b16d2febf38bb/cytoolz-0.10.1.tar.gz
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        def __repr__(self):
            return '{.__class__.__name__}{!r}'.format(
                self, tuple(reversed((self.first, ) + self.funcs)))

        def __eq__(self, other):
       ^
    ------------------------------------------------------------

    cytoolz/functoolz.pyx:518:4: Special method __eq__ must be implemented via __richcmp__

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __eq__(self, other):
            if isinstance(other, Compose):
                return other.first == self.first and other.funcs == self.funcs
            return NotImplemented

        def __ne__(self, other):
       ^
    ------------------------------------------------------------

    cytoolz/functoolz.pyx:523:4: Special method __ne__ must be implemented via __richcmp__
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4wjy8vvw/cytoolz/setup.py", line 87, in <module>
        ext_modules = cythonize(ext_modules, force=not is_dev)
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1027, in cythonize
        cythonize_one(*args)
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1149, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: cytoolz/functoolz.pyx
    [1/5] Cythonizing cytoolz/dicttoolz.pyx
    [2/5] Cythonizing cytoolz/functoolz.pyx

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4wjy8vvw/cytoolz/
```

```
$ python3 --version
Python 3.6.8
$ uname -a
Linux ubp52 5.2.9-050209-generic #201908160940 SMP Fri Aug 16 09:42:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I also get the same error when running:
```
$ pip3 install ethereum-etl
```

**Comment by medvedev1088** [comment]
See if the answer here helps https://unix.stackexchange.com/questions/519078/vapoursynth-installation-problems

**Comment by meowsbits** [comment]
Yep, that did it. Thanks!
