### ISSUE TITLE
Error encountered after Istanbul hardfork

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#193]
We encountered the error on December 9.  
**It seems to be caused by Istanbul hardfork.**  
**We are trying to figure it by updating parity and go ethereum client in our server.
Does it mean that we should update the parity and go ethereum client version frequently?** It is very troublesome.

The error is listed below:
**Symbolic Execution not available: No module named 'mythril'**
Traceback (most recent call last):
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 51, in get_block_range_for_timestamps
    end_block_bounds = self._graph_operations.get_bounds_for_y_coordinate(end_timestamp)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/graph_operations.py", line 40, in get_bounds_for_y_coordinate
    result = self._get_bounds_for_y_coordinate_recursive(y, *initial_bounds)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/graph_operations.py", line 45, in _get_bounds_for_y_coordinate_recursive
    raise OutOfBoundsError('y coordinate {} is out of bounds for points {}-{}'.format(y, start, end))
ethereumetl.service.graph_operations.OutOfBoundsError: y coordinate 1575935999 is out of bounds for points (1,1438269988)-(9069000,1575764710)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blockchain/anaconda3/bin/ethereumetl", line 11, in <module>
    sys.exit(cli())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/cli/export_all.py", line 116, in export_all
    output_dir, provider_uri, max_workers, export_batch_size)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_all_common.py", line 72, in export_all_common
    for batch_start_block, batch_end_block, partition_dir in partitions:
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/cli/export_all.py", line 76, in get_partitions
    batch_start_block, batch_end_block = eth_service.get_block_range_for_date(start_date)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 37, in get_block_range_for_date
    return self.get_block_range_for_timestamps(start_datetime.timestamp(), end_datetime.timestamp())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 53, in get_block_range_for_timestamps
    raise OutOfBoundsError('The existing blocks do not completely cover the given time range') from e
ethereumetl.service.graph_operations.OutOfBoundsError: The existing blocks do not completely cover the given time range

**Comment by medvedev1088** [comment]
> Does it mean that we should update the parity and go ethereum client version frequently?

Yes every time there is a hardfork the clients needs to be updated. There were frequent hardforks in December last year unfortunately, which might have caused trouble for many.
