### ISSUE TITLE
Error encounted while syncing data after May 17 2020

### ISSUE THREAD

**Issue by cxd1995** [blockchain-etl/ethereum-etl#218]
**We have been collecting data from Ethereum using ethereum-etl for years. But recently we have encountered an error. More specifically, the error started from May 17 2020. The error is copied below. Since there is no fork in Ethereum blockchain recently, we could not figure out the reason.**
 
Symbolic Execution not available: No module named 'mythril'
Traceback (most recent call last):
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 51, in get_block_range_for_timestamps
    end_block_bounds = self._graph_operations.get_bounds_for_y_coordinate(end_timestamp)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/graph_operations.py", line 40, in get_bounds_for_y_coordinate
    result = self._get_bounds_for_y_coordinate_recursive(y, *initial_bounds)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/graph_operations.py", line 45, in _get_bounds_for_y_coordinate_recursive
    raise OutOfBoundsError('y coordinate {} is out of bounds for points {}-{}'.format(y, start, end))
ethereumetl.service.graph_operations.OutOfBoundsError: y coordinate 1590364799 is out of bounds for points (1,1438269988)-(10120023,1590209309)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blockchain/anaconda3/bin/ethereumetl", line 11, in <module>
    sys.exit(cli())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/cli/export_all.py", line 116, in export_all
    output_dir, provider_uri, max_workers, export_batch_size)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_all_common.py", line 72, in export_all_common
    for batch_start_block, batch_end_block, partition_dir in partitions:
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/cli/export_all.py", line 76, in get_partitions
    batch_start_block, batch_end_block = eth_service.get_block_range_for_date(start_date)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 37, in get_block_range_for_date
    return self.get_block_range_for_timestamps(start_datetime.timestamp(), end_datetime.timestamp())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_service.py", line 53, in get_block_range_for_timestamps
    raise OutOfBoundsError('The existing blocks do not completely cover the given time range') from e
ethereumetl.service.graph_operations.OutOfBoundsError: The existing blocks do not completely cover the given time range

**Comment by medvedev1088** [comment]
Interesting. Looks like the node is not fully synced. Check what's the latest block number returned by the node and whether it's outside the date you're trying to export.

PS: I haven't noticed any issues in production.
