### ISSUE TITLE
error: The method eth_newFilter does not exist/is not available

### ISSUE THREAD

**Issue by dportabella** [blockchain-etl/ethereum-etl#220]
```
$ export_token_transfers --start-block 0 --end-block 500000 --provider-uri https://mainnet.infura.io/v3/239a1d18eba14f0f9dc1c882de0dc872 --output token_transfers.csv

Symbolic Execution not available: No module named 'mythril'
pyetherchain not available: No module named 'pyetherchain'
2020-07-13 19:19:41,224 - ProgressLogger [INFO] - Started work. Items to process: 500001.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/blockchainetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_token_transfers_job.py", line 62, in _export
    total_items=self.end_block - self.start_block + 1
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 59, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/usr/local/lib/python3.7/site-packages/ethereumetl/jobs/export_token_transfers_job.py", line 77, in _export_batch
    event_filter = self.web3.eth.filter(filter_params)
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 332, in filter
    [filter_params],
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method eth_newFilter does not exist/is not available'}
```

**Comment by medvedev1088** [comment]
Infura doesn't support this method. You will need another node provider or to run a node yourself.
