### ISSUE TITLE
Streaming traces in PostgreSQL with Geth trying to call Parity trace_block method

### ISSUE THREAD

**Issue by rjdenis** [blockchain-etl/ethereum-etl#223]
When streaming into DB with command "ethereumetl stream -e trace --lag 3 --provider-uri file:/home/ether/.ethereum/geth.ipc --output=postgresql+pg8000://root:@127.0.0.1:5432/ethereum" it seems that streamer trying to use the Parity trace_block method, instead Geth debug RPC, meanwhile "ethereumetl export_geth_traces" working nice with Geth without errors.

2020-08-28 19:30:43,246 - root [INFO] - Using file:/home/ether/.ethereum/geth.ipc
2020-08-28 19:30:43,385 - root [INFO] - Current block 10750259, target block 10749255, last synced block 10749254, blocks to sync 1
2020-08-28 19:30:43,386 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-28 19:30:43,387 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-28 19:30:43,388 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.002165.
2020-08-28 19:30:43,388 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-28 19:30:43,394 - root [ERROR] - An exception occurred while syncing block data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/blockchainetl/streaming/streamer.py", line 77, in _do_stream
    synced_blocks = self._sync_cycle()
  File "/usr/local/lib/python3.6/dist-packages/blockchainetl/streaming/streamer.py", line 98, in _sync_cycle
    self.blockchain_streamer_adapter.export_all(self.last_synced_block + 1, target_block)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/streaming/eth_streamer_adapter.py", line 61, in export_all
    traces = self._export_traces(start_block, end_block)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/streaming/eth_streamer_adapter.py", line 157, in _export_traces
    job.run()
  File "/usr/local/lib/python3.6/dist-packages/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_traces_job.py", line 104, in _end
    self.batch_work_executor.shutdown()
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 97, in shutdown
    self.executor.shutdown()
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/usr/local/lib/python3.6/dist-packages/ethereumetl/jobs/export_traces_job.py", line 89, in _export_batch
    json_traces = self.web3.parity.traceBlock(block_number)
  File "/usr/local/lib/python3.6/dist-packages/web3/parity.py", line 46, in traceBlock
    [block_identifier]
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'the method trace_block does not exist/is not available'}
2020-08-28 19:33:39,121 - root [INFO] - Nothing to sync. Sleeping for 10 seconds...
2020-08-28 19:37:28,978 - root [INFO] - Current block 10750293, target block 10749255, last synced block 10749254, blocks to sync 1
2020-08-28 19:37:28,979 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-28 19:37:28,980 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-28 19:37:28,980 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.001818.
2020-08-28 19:37:28,981 - ProgressLogger [INFO] - Started work. Items to process: 1.

**Comment by medvedev1088** [comment]
Thanks for reporting this. 

Geth is not supported yet for the stream command, only parity.

**Comment by rjdenis** [comment]
@medvedev1088 with Parity everything is working okay except stream trace in PostgreSQL again, the "traces" table is empty even if I execute command "ethereumetl stream -e trace --provider-uri file:/usr/local/share/openethereum/jsonrpc.ipc --output=postgresql+pg8000://root:@127.0.0.1:5432/ethereum". This situation is only with traces, other params (log, transactions etc) are working okay with database. Traces are working in console too with ConsoleItemExporter, so I think that the issue is somewhere in PostgresItemExporter, but there's no errors in log, just empty database...

...
2020-08-31 14:06:03,577 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-31 14:06:03,579 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-31 14:06:03,579 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.002330.
2020-08-31 14:06:03,580 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-31 14:06:03,583 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-31 14:06:03,584 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.004086.
2020-08-31 14:06:03,584 - root [INFO] - Exporting with PostgresItemExporter
2020-08-31 14:06:03,584 - root [INFO] - Writing last synced block 3448371
2020-08-31 14:06:03,588 - root [INFO] - Current block 3505755, target block 3448372, last synced block 3448371, blocks to sync 1
2020-08-31 14:06:03,588 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-31 14:06:03,591 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-31 14:06:03,591 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.003230.
2020-08-31 14:06:03,592 - ProgressLogger [INFO] - Started work. Items to process: 1.
2020-08-31 14:06:03,604 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2020-08-31 14:06:03,604 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.012496.
2020-08-31 14:06:03,605 - root [INFO] - Exporting with PostgresItemExporter
2020-08-31 14:06:03,606 - root [INFO] - Writing last synced block 3448372
...

**Comment by theweilu** [comment]
> Thanks for reporting this.
> 
> Geth is not supported yet for the stream command, only parity.

Is there a plan to support Geth for streaming traces?
