### ISSUE TITLE
cannot pip install due to newer python version

### ISSUE THREAD

**Issue by sui414** [blockchain-etl/ethereum-etl#224]
```
danningsui@DanningrkLaptop ~ % pip3 install ethereum-etl -v
Using pip 20.2.3 from /Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-ephem-wheel-cache-ew4hv4zk
Created temporary directory: /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-req-tracker-c_3us7do
Initialized build tracking at /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-req-tracker-c_3us7do
Created build tracker: /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-req-tracker-c_3us7do
Entered build tracker: /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-req-tracker-c_3us7do
Created temporary directory: /private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-install-k35l6dlw
1 location(s) to search for versions of ethereum-etl:
* https://pypi.org/simple/ethereum-etl/
Fetching project page and analyzing links: https://pypi.org/simple/ethereum-etl/
Getting page https://pypi.org/simple/ethereum-etl/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/ethereum-etl/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/ethereum-etl/ HTTP/1.1" 304 0
  Link requires a different Python (3.8.2 not in: '>=3.6.0,<3.7.0'): https://files.pythonhosted.org/packages/a4/8a/bece629ce70b1f3574fba55a91949a55eee0a4ad000e8e4461ea0b0e9230/ethereum-etl-1.0.0.tar.gz#sha256=136e5f31c9bcc97cb3bd5b090077e75f2a6fee5357ff5ebdcca906171b452af5 (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.6.0,<3.7.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/f8/37/9ba562480d1c870399e71accf83ac4f6142ed65abed9276ed5f64d331797/ethereum-etl-1.2.0.tar.gz#sha256=a01e0799cb9f1f56abc6a7e10165d02e449c026015dd1d71952156cd3095fde9 (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/9b/20/fae19833097a9c26c1114acf38793ddc185b446847ae862afba47ea465ec/ethereum-etl-1.2.1.tar.gz#sha256=28bea2377a606885064548941e692c52fa0d773dbef9a0e22d142b89e113c1aa (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/e5/08/ce53609361f4966e440dcbc7ed51d015d16f66abf341aa9987d7b017260d/ethereum-etl-1.2.2.tar.gz#sha256=1e2bffe3070c2ab325d0b6c6fdaaa9581c924ca5d4aa79c28146ebafbaed9973 (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/cc/29/3ffae2ea8d88aa4fd92bcb25663a19ed45987c4fc3c18ff4d4add940bce9/ethereum-etl-1.2.3.tar.gz#sha256=c63889e70aa7c7bc55196ad810c937a1ad029377158c800e82e82abfdf5ef17f (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/c7/9c/d1e41dd5e7a049327b9e785ae9c676cb8d9787c168e8797317c096b3d464/ethereum-etl-1.2.4.tar.gz#sha256=d8675c83b71bac508ee2855d70c9096b5d80fc5ba9531638c90dd476cf9f25e8 (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/79/fc/1159c489f8675f755de1b677ac45246d430846c366c6c28461d609377b94/ethereum-etl-1.3.0.tar.gz#sha256=bd779ffb40954da2b98d8dfdfba30dd1828eaa1170d89032d3bf96bc271c2b4e (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/40/b3/ba3f2d053fc403e55fcc17740858579ff5e3a630b864f6b153bc4f763ef2/ethereum-etl-1.3.1.tar.gz#sha256=9c5119fde063d264873c72af43964dee5b83d72943625aa7c435efdc642504bd (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/fb/65/84c4f4bcf210250ba98d296e96ca22c5c8413c9d9b7f56d36c09e2c06465/ethereum-etl-1.4.0.tar.gz#sha256=1a52dbdbc4964d261d55e652dc7707948ab65163512e28f5295b829c00417f5b (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/26/2a/0f792d476bec5ad97b5d1c2439a2fbcb37a16d6708cc5e85ba50c9b4e0a0/ethereum-etl-1.4.1.tar.gz#sha256=2ec8911c63700362d610a43c02a84dcf2401e28df4f6cc2b059d9ec5a70d8d7f (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/15/e7/e2d364d600a0bc54017ca63640e84c8ab4734889f665c41a4a2e132c2bb1/ethereum-etl-1.5.1.tar.gz#sha256=dc7ff3b71e5d869643091b947f76a6bfe8ab38d6babeec207252487ed86c3f0f (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
  Link requires a different Python (3.8.2 not in: '>=3.5.3,<3.8.0'): https://files.pythonhosted.org/packages/f3/94/8d8d56165dc3d4cf8ec935a9f4a5d3a1c6df577f4bf11dcebca70581c26b/ethereum-etl-1.5.2.tar.gz#sha256=c8aa7e4bef026f87e5f23278efd3a2cec86d2b8e8db03494c284e805b1613187 (from https://pypi.org/simple/ethereum-etl/) (requires-python:>=3.5.3,<3.8.0)
Given no hashes to check 0 links for project 'ethereum-etl': discarding no candidates
ERROR: Could not find a version that satisfies the requirement ethereum-etl (from versions: none)
ERROR: No matching distribution found for ethereum-etl
Exception information:
Traceback (most recent call last):
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/Users/danningsui/Library/Python/3.8/lib/python/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for ethereum-etl
Removed build tracker: '/private/var/folders/2b/j5kf5kj53pl3vm5b3j9hlklr0000gn/T/pip-req-tracker-c_3us7do'
```

current python is 3.8:
```
danningsui@DanningrkLaptop ~ % python3 --version
Python 3.8.2
```

can you plz add support for newer python version, or it's better to downgrade python?

**Comment by medvedev1088** [comment]
Thanks for reporting this @sui414. 

I just published a new version that should work with Python 3.8 https://pypi.org/project/ethereum-etl/1.6.0/. Please check if you can use it.

**Comment by sui414** [comment]
Yes - worked perfectly. Thanks for fix!
