### ISSUE TITLE
Failing to Stream data to Postgresql DB

### ISSUE THREAD

**Issue by grgcmz** [blockchain-etl/ethereum-etl#232]
Hello! Thank you for your hard work wiht this project!
I'm encountering some issues when running the following command to stream into a postgres database:
```
ethereumetl stream --provider-uri file://$HOME/.local/share/openethereum/jsonrpc.ipc --start-block 0 --output postgresql+pg8000://postgres:password@127.0.0.1:5432/test -e block
```
This is the output I get. Same thing when trying to runn it without the `-e` option

```
ethereumetl stream --provider-uri file://$HOME/.local/share/openethereum/jsonrpc.ipc --start-block 0 --output postgresql+pg8000://postgres:password@127.0.0.1:5432/test -e block
Symbolic Execution not available: No module named 'mythril'
2021-01-09 12:24:00,016 - root [INFO] - Using file:///home/giorgio/.local/share/openethereum/jsonrpc.ipc
Traceback (most recent call last):
  File "/home/giorgio/.local/bin/ethereumetl", line 8, in <module>
    sys.exit(cli())
  File "/home/giorgio/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/giorgio/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/giorgio/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/giorgio/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/giorgio/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/giorgio/.local/lib/python3.8/site-packages/ethereumetl/cli/stream.py", line 70, in stream
    item_exporter=create_item_exporter(output),
  File "/home/giorgio/.local/lib/python3.8/site-packages/ethereumetl/streaming/item_exporter_creator.py", line 40, in create_item_exporter
    from blockchainetl.jobs.exporters.postgres_item_exporter import PostgresItemExporter
  File "/home/giorgio/.local/lib/python3.8/site-packages/blockchainetl/jobs/exporters/postgres_item_exporter.py", line 27, in <module>
    from blockchainetl.jobs.exporters.converters.composite_item_converter import CompositeItemConverter
ModuleNotFoundError: No module named 'blockchainetl.jobs.exporters.converters' 
```

The Database is running, openethereum is also syncing. Pretty much all the scripts otherwise run, so the path and such should be correct.

Thanks for yout help in advance:)

**Comment by medvedev1088** [comment]
Thanks for reporting!

Not sure what the problem is. Try upgrading to v1.6.1 and see if it works. Just now I published a fix that might help.

**Comment by grgcmz** [comment]
Thank you so much! It is now working correctly with the update! 
Do you have an idea when contracts and tokens will be supported in the streaming command? :)
