### ISSUE TITLE
ValueError: {'code': -32000, 'message': 'execution reverted'}

### ISSUE THREAD

**Issue by Blazar221** [blockchain-etl/ethereum-etl#236]
Recently when I ran export_all, it crashed when exporting tokens, and I got this:
--------------------------------------------------------------------------------------
2021-01-06 13:08:04,246 - ProgressLogger [INFO] - Started work.
Traceback (most recent call last):
  File "/home/blockchain/anaconda3/bin/ethereumetl", line 11, in <module>
    sys.exit(cli())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/cli/export_all.py", line 116, in export_all
    output_dir, provider_uri, max_workers, export_batch_size)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_all_common.py", line 282, in export_all_common
    job.run()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_tokens_job.py", line 55, in _end
    self.batch_work_executor.shutdown()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 65, in shutdown
    self.executor.shutdown()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/home/blockchain/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/blockchain/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_tokens_job.py", line 43, in _export
    self.batch_work_executor.execute(self.token_addresses_iterable, self._export_tokens)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/home/blockchain/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/blockchain/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/blockchain/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_tokens_job.py", line 47, in _export_tokens
    self._export_token(token_address)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/jobs/export_tokens_job.py", line 50, in _export_token
    token = self.token_service.get_token(token_address)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_token_service.py", line 41, in get_token
    decimals = self._call_contract_function(contract.functions.decimals())
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_token_service.py", line 60, in _call_contract_function
    default_value=None)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_token_service.py", line 76, in call_contract_function
    raise ex
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/ethereumetl/service/eth_token_service.py", line 70, in call_contract_function
    result = func.call()
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/web3/contract.py", line 1120, in call
    **self.kwargs
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/web3/contract.py", line 1369, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/web3/eth.py", line 294, in call
    [transaction, block_identifier],
  File "/home/blockchain/anaconda3/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'execution reverted'}
-------------------------------------------------------------------------------
However, I can still find tokens.csv in the target output directory, only with part of data, so I wonder why this happen. Your help will be highly appreciated!

**Comment by Blazar221** [comment]
Ok I just figured out my ethereumetl was too old, I cloned the latest version and it worked well, although this warning was not eliminated.
