### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by dcoder2099** [blockchain-etl/ethereum-etl#264]
When attempting to use EthTokenService to retrieve the token '0x74956d9744340A9f127d1BBffecEf36D93b80Baa', a UnicodeDecodeError occurs.

As best I can tell, this is because of a function execution using the ERC20_ABI_ALTERNATIVE_1 interface.

Here is some interactive output:

```
$ python
Python 3.7.10 (default, Jun 24 2021, 15:16:33)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3 import Web3
>>> from ethereumetl.providers.auto import get_provider_from_uri
>>> from ethereumetl.service.eth_token_service import EthTokenService
>>> from ethereumetl.jobs.export_tokens_job import clean_user_provided_content
>>> token_address = '0x74956d9744340A9f127d1BBffecEf36D93b80Baa'
>>> provider_uri = 'https://mainnet.infura.io/v3/7aef3f0cd1f64408b163814b22cc643c'
>>> web3 = Web3(get_provider_from_uri(provider_uri))
>>> svc = EthTokenService(web3, clean_user_provided_content)
>>> svc.get_token(token_address)
[...NOTE: Two exceptions occur prior to this one that are ignored...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../ethereum-etl/ethereumetl/service/eth_token_service.py", line 49, in get_token
    symbol = self._bytes_to_string(symbol)
  File "/.../ethereum-etl/ethereumetl/service/eth_token_service.py", line 96, in _bytes_to_string
    b = b.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Calling `symbol()` and `SYMBOL()` on the normal contract both throw exceptions that are ignored.

Calling `symbol()` on `contract_alternative_1` returns a strange byte-string:

```
>>> from ethereumetl.erc20_abi import ERC20_ABI_ALTERNATIVE_1
>>> alt_contract = web3.eth.contract(address=token_address, abi=ERC20_ABI_ALTERNATIVE_1)
>>> alt_contract.functions.symbol().call()
b'\x80rg\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> some_bytes = _
>>> some_bytes.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
>>>
```

And that's what's throwing the error, which isn't being ignored... not sure if it should be or if it's important.

Any ideas how I can move beyond this? This surfaced while I was attempting to export using:

```
$ ethereumetl export_all -s 9954300 -e 9954399 -p ... -o ...
```

Ethereumetl does not exit cleanly.

**Comment by medvedev1088** [comment]
@dcoder2099 thanks for reporting. This should be fixed in https://github.com/blockchain-etl/ethereum-etl/releases/tag/v1.7.2

Please try it out and let me know if you find other issues
