### ISSUE TITLE
Why am I getting 'Is the node fully synced?' error for trace,contract,token entity types when streaming?

### ISSUE THREAD

**Issue by loganbonsignore** [blockchain-etl/ethereum-etl#279]
Hello, I am using ethereum-etl to stream data. I am using my own OpenEthereum node as the data source. An example of my stream command looks something like this:

```bash
ethereumetl stream --provider-uri=file:///home/path/to/jsonrpc.ipc --entity-types=block,transaction,log,token_transfer,trace,contract,token --all-other-flags...
```

After running this, I am receiving this error message asking if my node is fully synced. 

```bash
2021-11-02 00:43:15,404 - root [INFO] - Using file:///home/ubuntu/open_ethereum/storage/jsonrpc.ipc
2021-11-02 00:43:15,419 - root [INFO] - Current block 13534476, target block 13502398, last synced block 13502298, blocks to sync 100
2021-11-02 00:43:15,779 - ProgressLogger [INFO] - Started work. Items to process: 100.
2021-11-02 00:43:16,310 - ProgressLogger [INFO] - 50 items processed. Progress is 50%.
2021-11-02 00:43:16,318 - ProgressLogger [INFO] - 100 items processed. Progress is 100%.
2021-11-02 00:43:16,319 - ProgressLogger [INFO] - Finished work. Total items processed: 100. Took 0:00:00.539370.
2021-11-02 00:43:16,319 - ProgressLogger [INFO] - Started work. Items to process: 100.
2021-11-02 00:43:16,332 - root [ERROR] - An exception occurred while syncing block data.
Traceback (most recent call last):
  File "/home/ubuntu/sonar-etl/sonaretl/blockchainetl/streaming/streamer.py", line 77, in _do_stream
    synced_blocks = self._sync_cycle()
  File "/home/ubuntu/sonar-etl/sonaretl/blockchainetl/streaming/streamer.py", line 102, in _sync_cycle
    self.blockchain_streamer_adapter.export_all(self.last_synced_block + 1, target_block)
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/streaming/eth_streamer_adapter.py", line 61, in export_all
    traces = self._export_traces(start_block, end_block)
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/streaming/eth_streamer_adapter.py", line 157, in _export_traces
    job.run()
  File "/home/ubuntu/sonar-etl/sonaretl/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/jobs/export_traces_job.py", line 104, in _end
    self.batch_work_executor.shutdown()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/batch_work_executor.py", line 97, in shutdown
    self.executor.shutdown()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ubuntu/sonar-etl/sonaretl/blockchainetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/jobs/export_traces_job.py", line 65, in _export
    self.batch_work_executor.execute(
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/batch_work_executor.py", line 59, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/home/ubuntu/sonar-etl/sonaretl/ethereumetl/jobs/export_traces_job.py", line 92, in _export_batch
    raise ValueError('Response from the node is None. Is the node fully synced?')
ValueError: Response from the node is None. Is the node fully synced?
```

I can confirm my node is fully synced using the JSON RPC.

```bash
{"jsonrpc":"2.0","result":false,"id":1}
```

One thing to note is the stream is successful when using a subset of entity types:
```bash
ethereumetl stream --provider-uri=file:///home/path/to/jsonrpc.ipc --entity-types=block,transaction,log,token_transfer --all-other-flags...
```

Do you know what the issue could be here? Im thinking it has to do with the way my node is configured but wanted to check here as well.  

This is the command I used to launch the OpenEthereum node:
```bash
./openethereum --chain=ethereum --base-path=storage/ --db-path=/mnt/nvm/ether --jsonrpc-hosts=all
```

Thanks for your reply.

**Comment by medvedev1088** [comment]
You may need to check that openethereum is started with tracing = "on" option enabled and that trace_block API is enabled

**Comment by loganbonsignore** [comment]
Thanks!
