### ISSUE TITLE
Can't export data, when geth is fully synced

### ISSUE THREAD

**Issue by artemg** [blockchain-etl/ethereum-etl#297]
Can't export data, when geth is fully synced. geth is fully synced in full mode (eth.syncing = false), and when exporting data getting error:

`ethereumetl export_all -s 0 -e 50000 -b 100000  --provider-uri file:///mnt/geth/geth.ipc -o output
`

```
2022-01-05 02:14:34,636 - BatchWorkExecutor [ERROR] - An exception occurred while executing work_handler.
Traceback (most recent call last):
  File "/root/etl/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/root/etl/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/root/etl/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/root/etl/ethereum-etl/ethereumetl/utils.py", line 71, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/root/etl/ethereum-etl/ethereumetl/utils.py", line 82, in rpc_response_to_result
    raise RetriableValueError(error_message)
ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'result': None}. Make sure Ethereum node is synced.
```

```
> eth.getBlock('latest')
{
  baseFeePerGas: 88764178311,
  difficulty: 12809151827013907,
  extraData: "0x486976656f6e20686b",
  gasLimit: 30105076,
  gasUsed: 3978803,
  hash: "0xa4ff3e289d24e487de36f2de42ffd0362882dcc1e989cfa19f17f6e78eb4a99a",
  logsBloom: "0x00241010218c00a150000490e500120100402402000000810c11000444201001342200000000212146004880409001002a02820008202200005009011020612010050000000007280b0011582400202104080001801410024c0204708064c082120098040a0089400540a82010d00c40c06001000040040010904810000804100810809a20000002024a0040400a000008002041412000190009004a001200200aa18060344a2414200040c20814000c584020800000208405280020102854240200000281080400240801090001014280282824000b4a12040c0120921220008811210a06a010410004b60012020a6000404008200001510000080168008000",
  miner: "0x1ad91ee08f21be3de0ba2ba6918e714da6b45836",
  mixHash: "0xb956ffbb6f6e7a2dae9f483c7b5b50bceb23db77a4ea0acbc84e386581bd591a",
  nonce: "0x8cd33d62fa907512",
  number: 13942727,
  parentHash: "0xf4fddaf1646439b67caf7b3d217ea89af3f43863074db2c181ba0d094c9b1573",
  receiptsRoot: "0x53d78dbfc2fefc55cfcb7bfde887dcb9002ce79a18fe70b5ddbda80bc0c787ce",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 28512,
  stateRoot: "0x88c99fe1b6bd742e0b7d5f841dd165bef716462a96bce3275fbb21a5dd35bf85",
  timestamp: 1641348611,
  totalDifficulty: 3.8201114316493946423151e+22,
  transactions: ["0x5b8a97a9650256b841c918b87e8134a3fc0dfac2ed7e51c2f30c1535eeee057a", "0x935bd4592dc6a5968faac3a2e63f229444ba78dfa8d74a3dd8908fae4edf90eb", "0x1d08868494196865804b09cb2acfbdae296afdef4c43c67ac1ae73f6b024b8e6", "0x9150f96ea31d29124d60b8c2cbfb1e83ab417019a28dd54f2e726c69f5b36767", "0xf9b4aeaf5eee35dd755988cca426a583bee93db96fbe5eed4933b0f8f022a892", "0x6a6c478b2dcfd862d252f2212c2056051ef4325d315a84c6f52029e3d1f37e32", "0x6f83e8028c78f426e83d5deff16db4e8a4f90fbbdde9f1378734fad3533d5fdc", "0xe9f0ba99cc416a5213b8834d71200478ef1610aa54a55f7c1e06c96c0869305d", "0x17fc2db56903710a3aa7bed8eda03dd466a280c110c5f6126539b32aabca6a32", "0xb7f893bbf045b2ae30ca55926c88bf3a62e77024921467dc385753d5bbc282ef", "0x9e8274ce3972ebae0ed1172696dd8ec84da517f7f31b01b612f6c51e975d4414", "0xcf16c52fdf75539b7c871a17d060289b8153478ba5f39350ebeb8b4b04d3008d", "0x653d3a96f1571e27b68dbb71bf97af25bc10a9e3548fc74d59b72e374d3193a8", "0x5594ce93365903093ec9a1d90cb037826c285888b36998bf19b10178f7f638e9", "0x82945ef0aadc68bdebc24800c196f4ed1b2dc173493f21c9a6dec3b78cc16e6d", "0x0c306067d88b3bdad5bc22faa28bc67fc9c571ca8391663a62a3857e29228974", "0x5cb0d51b19f06fbc97935e66dbf448e854a7b50fbb7ced379a0fcc93ab0d0d37", "0x20eedfc6fa05477d8a65940fdd2718531df66a8fae44a0ac7cbc5c73a2f9f073", "0x5ae16a39e756c4acd8a80797c98ac682815148dfba104051ae99e6647fa22261", "0x8019ec68136ca552010de9c2aaba2f1759196af0ec841c1784c51d98ffc8565c", "0x08a70454fab577c5e87c4ac4b9a99416b146a0ae5d8bf920bbbb9c3f1db6095a", "0x8e2cd84616deba2a95913d5b5f98366f844e541c60673d16971db61417b802c6", "0x99a939784444020872c3c313b640fb79c98c25178e5fe26219b55027a10c4694", "0x2910315060a85c3a256c1d91371ba0dec7f01d8892eb7292054a4e4b5d470cd2", "0xcf233d877078e0c0621deb3d81754d056ef40fd67f0c4d48597dc78a18cbea02", "0x02c27fbc06e9620093a3f73466b776b60dda02818a811ecda1a0fcefea5cba6a", "0x07eee3895347d7b59e86a356d5a0406c73c25754c356bd9deda9fc0c62b493b8", "0x8a1367b29bf0c53247ffdb1fb8bab5202ca03556fb3c90e045787a2f782778b6", "0x47004c8161f1fc5a5be9a6e86f3f4278303a58ba8ac1df0cf3c72ad6bed5c5f6", "0x43a27418aa5d886cc2288601a35bde6f1d97b87476758b53c84dc94a80ca4a05", "0xf2f8f94edd182ac8c47d652a9caf46b6791c9b7f91ffed58404f78b2ed76078b", "0x00e56e9f3fca48d1421dbe048ace248c3a8e5982c940294cb867826dae4a17ec", "0xc299196d536bcd8380151b3045bd4b6a1926297cb42f9a7c9ece03e33dbc51fe", "0xb0a9fdf2c675c24941d844a7db3c2abe6278c2da1ef7e09f347cf48276a4195f", "0xc82344865b531897274a1d7cd7ad53860f94ab5327724b1b995c18882c7032d2", "0xad965bb629835b8b4f49ece5b064a8a940215eae39cbbb3bcacf2966b28d6892", "0x91cc1e073c3ff52844eef6c44744e1bcabde8a554c136437cab50775bb79b3c9", "0xc8d4d0ce566aa1947bc0499a8d3839a8e8306b08884af52f9b523cfcee5120b4", "0x4fad5962c1ff34b8142a07f1eb53bdc4831cee6107c01026cf7a4ba3d2b7dab4", "0x739f8bf482a23f0a45efef0ff98744cf8f0d444daf1c2858992a97544c83abc1", "0x9119b46443d54a31109116e95d0d0f40630025f772d514b06f5042c09978987b", "0xf581cd73cd123bbf4881ab545cab92c7b001eceea0b4d733f6fb6f9e94173b9e", "0xf28f606eed7b06faf48c28fc4ad20bca2cb7fbe2de2e11676b304716e0b7ad51", "0x976841eaf54df71a202cd71791ca9781ce570361cf8f7ffaad2ba21af1ec226d", "0x45a4b81a2ddf0b19f741eac37fdfe7bc1f60dbfb6ae6bcc7f96d31981faaba5e", "0xc466abdaa442f7c4f4e9edef14fc24ae1ec215e894f06be78748a5747ea8c700", "0xd6111ab76532407f6ba28a05fb1eb52bb613c499a579ee8f4a1aa80834489ba8", "0x68796de4f8cc23fcaa2d4c11041207387a80a9fe33ea77a227e64340f8513075", "0x38147599d08d75d6f69c2fab5ddd5db7c6b1b3ce970f71621a39b4a503e65ab2", "0xe33948cf5d6d75f3ac55f322b79a53029444760e12089b489d68a1530d676e39"],
  transactionsRoot: "0x11a5f30b4dd872d41a2f2b2dba5294aee94205bd5b0cc32a14dc6b9aa5117157",
  uncles: []
}
>  eth.syncing
false
> eth.blockNumber
13942732
```

**Comment by mike-seekwell** [comment]
there's an extra "/" in:

```
file:///mnt/geth/geth.ipc
```

**Comment by artemg** [comment]
That should not be an issue, but anyway I tried with "file://mnt/geth/geth.ipc" and got the same issue.
Also #279 seems to be the same issue.

**Comment by medvedev1088** [comment]
Does the process stop after emitting this error? There is a retry mechanism there so if the error is intermittent it will go through.

**Comment by artemg** [comment]
Ok, the issue is geth starting from 1.10 (?) stopped indexing old transactions by default. `--txlookuplimit 0` solves it
