### ISSUE TITLE
Building Docker image throws error

### ISSUE THREAD

**Issue by spencer-collins-kubrick** [blockchain-etl/ethereum-etl#317]
Hi there, when I attempt to build a Docker image based on `docker build -t ethereum-etl:latest .` it throws the following error: 

```
[+] Building 0.0s (1/2)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount404179178/Dockerfile: no such file or directory
```

Is this an issue with my configuration do you know or is it something else?

**Comment by medvedev1088** [comment]
Hey thanks for reporting. Have you checked out the repository before running the docker command? Dockerfile should be there https://github.com/blockchain-etl/ethereum-etl/blob/develop/Dockerfile

**Comment by spencer-collins-kubrick** [comment]
Hey, yep that works if I pull locally and build. Although I get a separate error when accessing infura with for example this command: `docker run -v ./output:/eth-etl/output eth-etl:latest export_all -s 0 -e 5499999 -b 100000 -p https://mainnet.infura.io`

I get this error trace:
2022-03-01 10:56:30,706 - root [ERROR] - An exception occurred while executing execute_with_retries. Retry #1
Traceback (most recent call last):
```
  File "/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute      
    work_handler(batch)
  File "/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 75, in _export_batch
    response = self.batch_web3_provider.make_batch_request(json.dumps(blocks_rpc))
  File "/ethereum-etl/ethereumetl/providers/rpc.py", line 39, in make_batch_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.6/site-packages/web3/utils/request.py", line 27, in make_post_request     
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status        
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mainnet.infura.io/
```

Am I meant to set up Infura access with my token somewhere?

**Comment by medvedev1088** [comment]
Correct you need to sign up for Infura or other node provider e.g. QuickNode
