### ISSUE TITLE
使用 ethereumetl 流 

### ISSUE THREAD

**Issue by zwyxnk** [blockchain-etl/ethereum-etl#366]
ethereumetl export_all -s 0 -e 9999999 -b 100000 -p file:///home/xnk/go-workspace/ETH/eth_data/geth.ipc -o output

2022-07-10 17:20:40,301 - ProgressLogger [INFO] - Started work.
2022-07-10 17:21:01,390 - BatchWorkExecutor [ERROR] - An exception occurred while executing work_handler.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/usr/local/lib/python3.8/dist-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/usr/local/lib/python3.8/dist-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/usr/local/lib/python3.8/dist-packages/ethereumetl/utils.py", line 71, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/usr/local/lib/python3.8/dist-packages/ethereumetl/utils.py", line 82, in rpc_response_to_result
    raise RetriableValueError(error_message)
ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'result': None}. Make sure Ethereum node is synced.
2022-07-10 17:21:01,397 - BatchWorkExecutor [INFO] - Reducing batch size to 50.

I don't know why the nodes are not synchronized. Is it necessary for nodes to be fully synchronized?

![2022-07-10 17-30-19 的屏幕截图](https://user-images.githubusercontent.com/92698811/178139169-6df9d3f5-2741-4839-bac4-63cc5a7fbbcf.png)

**Comment by loganbonsignore** [comment]
I'm seeing this same issue. I have a Geth node and using the ipc file to extract data like above.

Reverting to an old version of Web3 fixed it for me. Currently running version 4.7.2. Hoping to find a real solution.

**Comment by dbfreem** [comment]
I was trying to reproduce this issue and having trouble doing so. I am running a local node and running the command that you have above. @zwyxnk Is there anything you can think of that may make this more reproducible.

Also, @loganbonsignore can you provide more details about your issue? When you say you downgraded web3, are you saying you reverted back to a v1 version of ethereum-etl?

**Comment by zwyxnk** [comment]
> 



> I was trying to reproduce this issue and having trouble doing so. I am running a local node and running the command that you have above. @zwyxnk Is there anything you can think of that may make this more reproducible.
> 
> Also, @loganbonsignore can you provide more details about your issue? When you say you downgraded web3, are you saying you reverted back to a v1 version of ethereum-etl?

I used Ubuntu to deploy a full node of geth, but when synchronizing, there are always dozens of blocks that cannot be synchronized. Then use Ethereum ETL to obtain Ethereum data set, but failed. The reason for the error is that the block is not synchronized
