### ISSUE TITLE
Failed to transfer eth data to kinesis using ethereumetl stream

### ISSUE THREAD

**Issue by tsaol** [blockchain-etl/ethereum-etl#442]
version:ethereumetl, version 2.1.1 

I synchronized all the blocks, using geth client & lighthouse 4.10 and adopted the default dault snap method to synchronize all the blocks. I am trying  to extract the data into kinesis using ethereumetl, Accroding to documentation it is possible to do so

command：
```
ethereumetl stream  \
--provider-uri file:///home/ubuntu/.ethereum/geth.ipc \
--output=kinesis://blockchain-kinesis
```

![Screenshot 2023-04-25 at 00 06 27](https://user-images.githubusercontent.com/28560673/234054228-5db9399f-a528-4514-8969-696f71a15fda.png)

An exception occurred while executing block 46146
There is error info in logs.
```
2023-04-24 15:47:55,031 - root [INFO] - Nothing to sync. Sleeping for 10 seconds...
2023-04-24 15:48:05,045 - root [INFO] - Current block 17117132, target block 46147, last synced block 46146, blocks to sync 1
2023-04-24 15:48:05,045 - ProgressLogger [INFO] - Started work. Items to process: 1.
2023-04-24 15:48:05,046 - ProgressLogger [INFO] - 1 items processed. Progress is 100%.
2023-04-24 15:48:05,046 - ProgressLogger [INFO] - Finished work. Total items processed: 1. Took 0:00:00.001060.
2023-04-24 15:48:05,046 - ProgressLogger [INFO] - Started work.
2023-04-24 15:48:05,047 - BatchWorkExecutor [ERROR] - An exception occurred while executing work_handler.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/utils.py", line 71, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/utils.py", line 82, in rpc_response_to_result
    raise RetriableValueError(error_message)
ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'result': None}. Make sure Ethereum node is synced.
2023-04-24 15:48:05,047 - BatchWorkExecutor [INFO] - The batch of size 1 will be retried one item at a time.
2023-04-24 15:48:05,048 - root [ERROR] - An exception occurred while executing execute_with_retries. Retry #0
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/utils.py", line 71, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ethereumetl/utils.py", line 82, in rpc_response_to_result
    raise RetriableValueError(error_message)
ethereumetl.misc.retriable_value_error.RetriableValueError: result is None in response {'jsonrpc': '2.0', 'id': 0, 'result': None}. Make sure Ethereum node is synce
```

can anyone help

**Comment by GauthamramRavichandran** [comment]
Only archive node can export full block details in any block. the snap sync node can export full block details of latest 100 blocks alone. Try to stream latest block
