### ISSUE TITLE
Setting batch-size value above 100 for export_receipts_and_logs crush the program

### ISSUE THREAD

**Issue by megalepozy** [blockchain-etl/ethereum-etl#470]
Ethereum-ETL version 2.3.1
Getting data from Erigon (I think 2.55.1, will check if needed)

I ran the following command:
> ethereumetl export_receipts_and_logs --transaction-hashes transaction_hashes.txt --provider-uri http://172.19.0.2:8545 --receipts-output receipts.csv --logs-output logs.csv

The performance is way lower than what I can work with as it stands on about 1k transactions (items) per a second and I need to run over all of the blockchain... 

Checking the server performance I noticed the ethereum-etl is using less than 10% of a core and Erigon is also quite lazy so I suspect that the low speed happen because of the http protocol usage (what do you think? would love to get some feedback).

For a quick test I thought that maybe upping the --batch-size value to something like 5000 might be useful but when I did that (or any value above 100) I got the following error immediatly:

```
ethereumetl export_receipts_and_logs --batch-size 150 --transaction-hashes transaction_hashes.txt --provider-uri http://172.19.0.2:8545 --receipts-output receipts.csv --logs-output logs.csv
2024-01-09 16:47:37,375 - ProgressLogger [INFO] - Started work.
Traceback (most recent call last):
  File "/ethereum-etl/blockchainetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 63, in _export
    self.batch_work_executor.execute(self.transaction_hashes_iterable, self._export_receipts)
  File "/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 59, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/ethereum-etl/ethereumetl/utils.py", line 81, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/ethereum-etl/ethereumetl/utils.py", line 85, in rpc_response_to_result
    result = response.get('result')
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ethereumetl", line 33, in <module>
    sys.exit(load_entry_point('ethereum-etl', 'console_scripts', 'ethereumetl')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/ethereum-etl/ethereumetl/cli/export_receipts_and_logs.py", line 65, in export_receipts_and_logs
    job.run()
  File "/ethereum-etl/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 81, in _end
    self.batch_work_executor.shutdown()
  File "/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 97, in shutdown
    self.executor.shutdown()
  File "/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 63, in _fail_safe_execute
    work_handler(batch)
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 69, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/ethereum-etl/ethereumetl/utils.py", line 81, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/ethereum-etl/ethereumetl/utils.py", line 85, in rpc_response_to_result
    result = response.get('result')
AttributeError: 'str' object has no attribute 'get'

```

**Comment by megalepozy** [comment]
Just checked and this issue is happening also with `export_blocks_and_transactions`, probably happen with other commands as well

**Comment by megalepozy** [comment]
Btw in regards to the performance, I also played a bit with --max-workers (20, 12 & 8 workers) and the diff was negligible.

In general the CPU's r mostly waiting/idling, I still think that it's because I connect to Erigon using HTTP, will try to check tomorrow with IPC (need a separate RPC daemon for that)

**Comment by megalepozy** [comment]
So I found out that the problem was on Erigon side as I didn't set a flag of --rpc.batch.limit which default to 100.
I guess that ethereum etl error can be improved to return Erigon code instead of just crushing.

In regards to the performance, it did improve the performance of export_blocks_and_transactions considerably but it doesn't seems to change anything for export_receipts_and_logs which is my main issue (Seems like I'm reaching iops limit on the SSD).
