### ISSUE TITLE
Windows - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RaianeQC** [blockchain-etl/ethereum-etl#49]
C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master>python export_blocks_and_transactions.py --start-block 0 --end-block 500000 \ --ipc-path ~/Library/Ethereum/geth.ipc --blocks-output blocks.csv --transactions-output transactions.csv
Traceback (most recent call last):
  File "export_blocks_and_transactions.py", line 4, in <module>
    from ethereumetl.ipc import IPCWrapper
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\ipc.py", line 5, in <module>
    from web3.providers.ipc import get_default_ipc_path, PersistantSocket
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\web3\__init__.py", line 8, in <module>
    from web3.main import Web3  # noqa: E402
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\web3\main.py", line 26, in <module>
    from web3.providers.eth_tester import (
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\web3\providers\__init__.py", line 8, in <module>
    from .websocket import WebsocketProvider  # noqa: F401
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\web3\providers\websocket.py", line 9, in <module>
    import websockets
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\client.py", line 20, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from .compatibility import asyncio_ensure_future
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\compatibility.py", line 15
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax

**Comment by medvedev1088** [comment]
What version of python are you using?

**Comment by RaianeQC** [comment]
Version python 3.7

**Comment by RaianeQC** [comment]
I will install version python 3.5

**Comment by RaianeQC** [comment]
Now I have problem

Traceback (most recent call last):
  File "export_blocks_and_transactions.py", line 35, in <module>
    job.run()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\base_job.py", line 7, in run
    self._end()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 57, in _end
    super()._end()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 56, in _end
    self.executor.shutdown()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 16, in shutdown
    self._check_completed_futures()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\base_job.py", line 5, in run
    self._export()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 42, in _export
    self.executor.submit(self._fail_safe_export_batch, batch_start, batch_end)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 8, in submit
    self._check_completed_futures()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 50, in _fail_safe_export_batch
    self._export_batch(block_number, block_number)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 42, in _export_batch
    response = self.ipc_wrapper.make_request(json.dumps(blocks_rpc))
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\ipc.py", line 34, in make_request
    with self._lock, self._socket as sock:
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 45, in __enter__
    self.sock = self._open()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 58, in _open
    return get_ipc_socket(self.ipc_path)
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 26, in get_ipc_socket
    return NamedPipe(ipc_path)
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\utils\windows.py", line 19, in __init__
    raise IOError(err)
OSError: (3, 'CreateFile', 'O sistema não pode encontrar o caminho especificado.')

**Comment by medvedev1088** [comment]
Seems you are using Windows. Try these instructions https://github.com/medvedev1088/ethereum-etl#running-in-windows

**Comment by medvedev1088** [comment]
In particular the file path should be `\\.\pipe\geth.ipc`

**Comment by RaianeQC** [comment]
Thanks, very much!

Sorry , but I have problem:

./export_all.sh: line 71: python3: command not found
2018-07-14 15:59:23 An error occurred. Quitting.

**Comment by RaianeQC** [comment]
I run in GIT Bash,  ./export_all.sh -s 0 -e 999999 -b 100000 -i '\\.\pipe\geth.ipc' -o output
 
But i have problem belove:

Traceback (most recent call last):
  File "export_blocks_and_transactions.py", line 35, in <module>
    job.run()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\base_job.py", line 7, in run
    self._end()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 57, in _end
    super()._end()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 56, in _end
    self.executor.shutdown()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 16, in shutdown
    self._check_completed_futures()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\base_job.py", line 5, in run
    self._export()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 42, in _export
    self.executor.submit(self._fail_safe_export_batch, batch_start, batch_end)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 8, in submit
    self._check_completed_futures()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 50, in _fail_safe_export_batch
    self._export_batch(block_number, block_number)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 42, in _export_batch
    response = self.ipc_wrapper.make_request(json.dumps(blocks_rpc))
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\ipc.py", line 34, in make_request
    with self._lock, self._socket as sock:
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 45, in __enter__
    self.sock = self._open()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 58, in _open
    return get_ipc_socket(self.ipc_path)
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\providers\ipc.py", line 26, in get_ipc_socket
    return NamedPipe(ipc_path)
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\site-packages\web3\utils\windows.py", line 19, in __init__
    raise IOError(err)

**Comment by medvedev1088** [comment]
After raise IOError(err) you have the same message as before? `OSError: (3, 'CreateFile', 'O sistema não pode encontrar o caminho especificado.')`
Check that geth is running. The message says that the ipc file doesn't exist.

**Comment by RaianeQC** [comment]
Thank very Much.

I have other problem:

Traceback (most recent call last):
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\base_job.py", line 5, in run
    self._export()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 42, in _export
    self.executor.submit(self._fail_safe_export_batch, batch_start, batch_end)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 8, in submit
    self._check_completed_futures()
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\executors\fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\batch_export_job.py", line 46, in _fail_safe_export_batch
    self._export_batch(batch_start, batch_end)
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 44, in _export_batch
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\jobs\export_blocks_job.py", line 44, in <listcomp>
    blocks = [self.block_mapper.json_dict_to_block(result) for result in results]
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\utils.py", line 25, in rpc_response_batch_to_results
    raise ValueError('result is null in response {}'.format(response_item))
ValueError: result is null in response {'result': None, 'jsonrpc': '2.0', 'id': 0}

**Comment by RaianeQC** [comment]
Thank you, you helped me a lot.

I'll study your script.

I'm very grateful.

**Comment by t2y** [comment]
It seems that https://github.com/blockchain-etl/ethereum-etl/issues/35 is the same cause as this. It's duplicated issue.
