### ISSUE TITLE
TypeError: Address must be provided as a string

### ISSUE THREAD

**Issue by Mushoz** [blockchain-etl/ethereum-etl#82]
I am running into the following traceback when running the command below. As far as I can tell, I followed the proper format as per the documentation. The entire command works fine without the --tokens argument, but in that case I would be extracting every erc-20 token transfer ever made, which is going to take a very very long time :)

```
jaap@Ubuntu-VM:~/ethereum-etl$ python3 export_token_transfers.py --start-block 0 --end-block 6139406 --provider-uri file:///home/jaap/.ethereum/geth.ipc --output ../Documents/transfers.csv --tokens 0xb056c38f6b7dc4064367403e26424cd2c60655e1
2018-08-13 12:38:39,960 - ProgressLogger [INFO] - Started work. Items to process: 6139407.
Traceback (most recent call last):
  File "export_token_transfers.py", line 60, in <module>
    job.run()
  File "/home/jaap/ethereum-etl/ethereumetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/jaap/ethereum-etl/ethereumetl/jobs/export_token_transfers_job.py", line 88, in _end
    self.batch_work_executor.shutdown()
  File "/home/jaap/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 65, in shutdown
    self.executor.shutdown()
  File "/home/jaap/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/jaap/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jaap/ethereum-etl/ethereumetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/home/jaap/ethereum-etl/ethereumetl/jobs/export_token_transfers_job.py", line 62, in _export
    total_items=self.end_block - self.start_block + 1
  File "/home/jaap/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/home/jaap/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/home/jaap/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jaap/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/home/jaap/ethereum-etl/ethereumetl/jobs/export_token_transfers_job.py", line 77, in _export_batch
    event_filter = self.web3.eth.filter(filter_params)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/eth.py", line 332, in filter
    [filter_params],
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 47, in apply_formatters
    formatted_params = formatter(params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/formatters.py", line 41, in apply_formatter_at_index
    yield formatter(item)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/rpc_abi.py", line 69, in apply_abi_formatters_to_dict
    [data[field] for field in fields],
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/abi.py", line 442, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 589, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 565, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/abi.py", line 474, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/formatters.py", line 115, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/formatters.py", line 102, in map_collection
    return datatype(map(func, collection))
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/formatters.py", line 114, in recurse
    return recursive_map(func, item)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/formatters.py", line 116, in recursive_map
    return func(items_mapped)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/abi.py", line 471, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/normalizers.py", line 45, in wrapper
    modified = to_wrap(abi_type, data)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/normalizers.py", line 124, in abi_address_to_hex
    validate_address(data)
  File "/home/jaap/.local/lib/python3.6/site-packages/web3/utils/validation.py", line 152, in validate_address
    raise TypeError('Address {} must be provided as a string'.format(value))
TypeError: Address ['0xb056c38f6b7dc4064367403e26424cd2c60655e1'] must be provided as a string
```

**Comment by medvedev1088** [comment]
Thanks for reporting this. Please check your web3 version:

> $ pip show web3
> Name: web3
> Version: 4.4.1

Filtering by token address works fine for me. I guess it has to do with latest version of web3.py where they added address param validation https://github.com/ethereum/web3.py/blob/master/web3/utils/rpc_abi.py.

If that's the case then the issue should be submitted to web3.py as well because the address param should allow arrays https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter

> address: DATA|Array, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate.

**Comment by Mushoz** [comment]
This is my web3 version:

```
jaap@Ubuntu-VM:~/ethereum-etl$ pip3 show web3
Name: web3
Version: 4.5.0
```

Please let me know if this is indeed a bug with web3, because I will file a bug report upstream then. Thank you :)

**Comment by medvedev1088** [comment]
Yes this is a web3.py issue. You can submit a bug and the sample code that doesn't work but is supposed to is:

```
filter_params = {
            'fromBlock': 0,
            'toBlock': 1,
            'topics': '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
            'address': ['0xb056c38f6b7dc4064367403e26424cd2c60655e1']
        }

event_filter = web3.eth.filter(filter_params)
```

**Comment by medvedev1088** [comment]
@Mushoz any updates on this issue?
