### ISSUE TITLE
Cannot get export_all.sh function to run (or any others)

### ISSUE THREAD

**Issue by tucker-chambers** [blockchain-etl/ethereum-etl#99]
Hi there,
I am running geth, with the --ipcdisable flag because I am storing the blockchain data on an external HD and am therefore also using the --datadir flag. Everything is syncing fine and I have about 90% of the chain downloaded. On my local OSX, I have installed the ethereum-etl package (using Python 3.7) and can see all of the .py programs. However, I am getting the errors below. I am using the file where /geth (under it, /chaindata) and /keystore are stored.

Any suggestion would be greatly appreciated.
Thank you.

 

`TCC-mac:ethereum-etl tuckercahillchambers$ ./export_all.sh -s 0 -e 5800000 -b 100000 -p file://Volumes/HG Wells/ -o output
2018-10-01 10:37:54 Exporting blocks 00000000-00099999 to ./blocks/start_block=00000000/end_block=00099999/blocks_00000000_00099999.csv
2018-10-01 10:37:54 Exporting transactions from blocks 00000000-00099999 to ./transactions/start_block=00000000/end_block=00099999/transactions_00000000_00099999.csv
2018-10-01 10:37:56,441 - ProgressLogger [INFO] - Started work. Items to process: 100000.
Traceback (most recent call last):
  File "/Users/tuckercahillchambers/Desktop/ETL/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/Users/tuckercahillchambers/Desktop/ETL/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 75, in _export_batch
    response = self.batch_web3_provider.make_request(json.dumps(blocks_rpc))
  File "/Users/tuckercahillchambers/Desktop/ETL/ethereum-etl/ethereumetl/providers/ipc.py", line 57, in make_request
    with self._lock, self._socket as sock:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/providers/ipc.py", line 46, in __enter__
    self.sock = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/providers/ipc.py", line 59, in _open
    return get_ipc_socket(self.ipc_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/providers/ipc.py", line 30, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by medvedev1088** [comment]
If you can't use IPC you should enable rpc using `--rpc` https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options. Then use `-p http://localhost:8545` for `export_all.sh`

**Comment by tucker-chambers** [comment]
Thank you. The --rpc command and localhost ideas worked.

**Comment by tucker-chambers** [comment]
Also, what would you say is a reasonable timeframe for export_all.sh to complete its task (say, per 10,000 items)? Thanks again.
